general:
  me: voxel_cart.yml
  device: cuda:0
  driver: voxel_cart.py
  output: [local/tmp , 1] # root, iter

data:
  root: /home/moji/hdd/moji/data/h2reaction/all #AIMD/04/combined
  irc: /home/moji/hdd/moji/data/h2reaction/IRC/04_H2O+O_2OH.t
  reaction: 4 #[1,2,3,4,8,9,10,11,13,14,15,16,17,18,19]
  normal_mode: True
  size_nmode_max: 4000     # will be applied to both single and multiple reaction job
  cutoff: 5.0
  trsize_perrxn_max: 5000     # won't be applied to a single reaction job
  test_size: 1000
  val_size: 1000
  oversmpl: False
  oversmpl_l: ['ts']
  oversmpl_n: [1]
  random_states: 90
  cgem: False

model:
  mode: channelize
  pre_trained: False #/global/scratch/mojtabah/outputs/h2reaction/voxel_cart4/vc2/transfer/training_2/models/best_model_state.tar
  activation: ssp
  requires_dr: True
  grad_total_energy: True
  w_energy: 1.0
  w_force: 1.0
  w_f_mag: 0.0
  w_f_dir: 0.0
  atom_types: [1,8]
  grid_length: [3, 4, 6, 10]
  grid_size: 30
  n_filter: 128
  trainable_sigma: False
  dropout: False
  normalize_atomic: True

training:
  epochs: 500
  tr_batch_size: 12
  val_batch_size: 12
  tr_rotations: 4
  val_rotations: 4
  tr_frz_rot: False
  val_frz_rot: False
  tr_keep_original: False
  val_keep_original: True
  shuffle: True
  drop_last: True
  lr: 0.0005
  lr_scheduler: [plateau, 5, 5, 0.7, 1.0e-6]
#  lr_scheduler: [decay, 0.05]
  weight_decay: 0.0 #3.0e-5
  dropout: 0.0

checkpoint:
  log: 1
  val: 1
  model: 100
  verbose: True




