general:
  me: voxel_polar/voxel_polar.yml
  device: cuda:0
  driver: voxel_polar.py
  output: [voxel_polar/local/rxn4 , 1] # root, iter

data:
  root: /home/moji/hdd/moji/data/h2reaction/AIMD/04/combined
  irc: /home/moji/hdd/moji/data/h2reaction/IRC/04_H2O+O_2OH.t
  reaction: 4
  normal_mode: False
  cutoff: 5.0
  test_size: 1000
  val_size: 1000
  oversmpl: False
  oversmpl_l: ['ts']
  oversmpl_n: [1]
  random_states: 90

model:
  mode: channelize
  activation: ssp
  requires_dr: True
  w_energy: 1.0
  w_force: 1.0
  w_f_mag: 0.0
  w_f_dir: 0.0
  atom_types: [1,8]
  grid_length: 10.0 #[1., 2., 4., 6., 14.]
  grid_size: [50, 20, 40]
  n_filter: 128
  trainable_sigma: False
  smoothing_sigma: 1.5
  smoothing_kernel: [7,5,5]
  pooling_type: sum
  dropout: False
  normalize_atomic: True

training:
  epochs: 500
  tr_batch_size: 32
  val_batch_size: 32
  tr_rotations: 1
  val_rotations: 1
  tr_frz_rot: False
  val_frz_rot: False
  tr_keep_original: True
  val_keep_original: True
  shuffle: True
  drop_last: True
  lr: 0.0005
  lr_scheduler: [plateau, 5, 5, 0.7, 1.0e-6]
#  lr_scheduler: [decay, 0.05]
  weight_decay: 0.0 #3.0e-5
  dropout: 0.0

checkpoint:
  log: 1
  val: 1
  model: 100
  verbose: True




